# Generated by Django 5.2.3 on 2025-07-14 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pdf_app', '0004_alter_pdffile_is_solution'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolutionPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('year', models.PositiveIntegerField()),
                ('file', models.FileField(upload_to='solution_pdfs/')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solution_pdfs', to='pdf_app.subject')),
            ],
        ),
    ]
