# Generated by Django 5.2.3 on 2025-07-29 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solution_pdf', '0002_solutionfeedback_solutionsubject_solutiontopic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolutionUserQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solution_pdf.solutiontopic')),
            ],
        ),
    ]
