# Generated by Django 5.2.3 on 2025-07-29 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solution_pdf', '0003_solutionuserquery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solutionpdffile',
            old_name='is_question',
            new_name='is_solution',
        ),
        migrations.AlterField(
            model_name='solutionpdffile',
            name='file',
            field=models.FileField(upload_to='pdfs/'),
        ),
    ]
