# Generated by Django 5.2.3 on 2025-07-04 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_app', '0002_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdffile',
            name='is_solution',
            field=models.BooleanField(default=False, verbose_name='Is Solution PDF'),
        ),
    ]
