# Generated by Django 5.2.3 on 2026-02-12 06:30

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


def safe_rename_user_indexes(apps, schema_editor):
    """Drop old user indexes if they exist and create new ones. Skip if users table does not exist (old production DB)."""
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            "SELECT 1 FROM sqlite_master WHERE type='table' AND name='users'"
        )
        if not cursor.fetchone():
            return  # Old production DB: users table not created yet, skip index rename
        for old_name, new_name, table, column in [
            ('users_phone_idx', 'users_phone_af6883_idx', 'users', 'phone'),
            ('users_referral_idx', 'users_referra_98b351_idx', 'users', 'referral_code'),
        ]:
            cursor.execute(f'DROP INDEX IF EXISTS "{old_name}"')
            cursor.execute(f'CREATE INDEX IF NOT EXISTS "{new_name}" ON "{table}" ("{column}")')


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('pdf_app', '0002_add_payment_qr'),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_nepali', models.CharField(blank=True, max_length=200)),
                ('location', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=50)),
                ('total_students', models.IntegerField(default=0)),
                ('rank', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-total_students', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GroupMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messages_sent_today', models.IntegerField(default=0)),
                ('last_reset_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=15)),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('attempts', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('payment_type', models.CharField(choices=[('SUBSCRIPTION', 'Subscription'), ('SINGLE_PDF', 'Single PDF'), ('BULK_PDF', 'Bulk PDFs')], default='SUBSCRIPTION', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tier', models.CharField(blank=True, choices=[('GOLD', 'Gold - ₹499/semester'), ('DIAMOND', 'Diamond - ₹899/semester')], max_length=20, null=True)),
                ('screenshot', models.ImageField(upload_to='payment_screenshots/')),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('transaction_note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Verification'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PdfAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_used', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReferralReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_type', models.CharField(choices=[('AD_FREE_WEEK', '1 Week Ad-Free'), ('PREMIUM_FEATURE', 'Premium Feature'), ('PREMIUM_MONTH', '1 Month Premium'), ('PREMIUM_3MONTH', '3 Months Premium')], max_length=30)),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.CharField(blank=True, choices=[('BBS', 'BBS'), ('BCA', 'BCA'), ('BA', 'BA'), ('BSW', 'BSW'), ('BED', 'BED'), ('BSc', 'BSc'), ('OTHER', 'Other')], max_length=20)),
                ('year', models.IntegerField(blank=True, choices=[(1, '1st'), (2, '2nd'), (3, '3rd'), (4, '4th')], null=True)),
                ('section', models.CharField(blank=True, max_length=5)),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('verification_photo', models.ImageField(blank=True, null=True, upload_to='verification/')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_type', models.CharField(choices=[('COLLEGE', 'College'), ('PROGRAM', 'Program'), ('YEAR', 'Year')], max_length=20)),
                ('program', models.CharField(blank=True, max_length=20)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('total_messages', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('FREE', 'Bronze (Free)'), ('GOLD', 'Gold (₹499/sem)'), ('DIAMOND', 'Diamond (₹899/sem)')], default='FREE', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('pdfs_viewed', models.IntegerField(default=0)),
                ('messages_sent', models.IntegerField(default=0)),
                ('time_spent_minutes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserStreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.IntegerField(default=0)),
                ('longest_streak', models.IntegerField(default=0)),
                ('last_activity_date', models.DateField(auto_now=True)),
                ('total_days_active', models.IntegerField(default=0)),
                ('streak_frozen', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='pdffile',
            options={'ordering': ['-year', 'title']},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['topic', 'name']},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='userquery',
            options={'ordering': ['-submitted_at']},
        ),
        # Safe index rename: backup DB may not have old index names (drop if exists, create new)
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RenameIndex(
                    model_name='user',
                    new_name='users_phone_af6883_idx',
                    old_name='users_phone_idx',
                ),
                migrations.RenameIndex(
                    model_name='user',
                    new_name='users_referra_98b351_idx',
                    old_name='users_referral_idx',
                ),
            ],
            database_operations=[
                migrations.RunPython(safe_rename_user_indexes, migrations.RunPython.noop),
            ],
        ),
        migrations.AddField(
            model_name='pdffile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pdffile',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pdffile',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='pdf_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pdf_app.pdffile'),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='messagequota',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='message_quota', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['phone', '-created_at'], name='pdf_app_otp_phone_0bc2c7_idx'),
        ),
        migrations.AddField(
            model_name='payment',
            name='purchased_pdf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pdf_app.pdffile'),
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pdfaccess',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pdf_app.payment'),
        ),
        migrations.AddField(
            model_name='pdfaccess',
            name='pdf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdf_app.pdffile'),
        ),
        migrations.AddField(
            model_name='pdfaccess',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_accesses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referral',
            name='referred',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referred_by_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referral',
            name='referrer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_referrals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referralreward',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='pdf_app.college'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studygroup',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='pdf_app.college'),
        ),
        migrations.AddField(
            model_name='studygroup',
            name='members',
            field=models.ManyToManyField(related_name='study_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='pdf_app.studygroup'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='last_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_subscription', to='pdf_app.payment'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userbookmark',
            name='pdf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdf_app.pdffile'),
        ),
        migrations.AddField(
            model_name='userbookmark',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userstreak',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='streak', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['user', 'status'], name='pdf_app_pay_user_id_6fb019_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', '-created_at'], name='pdf_app_pay_status_49200a_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_id'], name='pdf_app_pay_payment_09fe0f_idx'),
        ),
        migrations.AddIndex(
            model_name='pdfaccess',
            index=models.Index(fields=['user', 'pdf'], name='pdf_app_pdf_user_id_072178_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pdfaccess',
            unique_together={('user', 'pdf')},
        ),
        migrations.AlterUniqueTogether(
            name='referral',
            unique_together={('referrer', 'referred')},
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['college', 'program', 'year'], name='pdf_app_stu_college_884690_idx'),
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['verification_status'], name='pdf_app_stu_verific_adb041_idx'),
        ),
        migrations.AddIndex(
            model_name='studygroup',
            index=models.Index(fields=['college', 'group_type'], name='pdf_app_stu_college_63834d_idx'),
        ),
        migrations.AddIndex(
            model_name='groupmessage',
            index=models.Index(fields=['group', '-created_at'], name='pdf_app_gro_group_i_4644aa_idx'),
        ),
        migrations.AddIndex(
            model_name='groupmessage',
            index=models.Index(fields=['group', 'id'], name='pdf_app_gro_group_i_0b9860_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['user', 'tier'], name='pdf_app_sub_user_id_0d034a_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['expires_at'], name='pdf_app_sub_expires_9ea6a9_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['user', 'date'], name='pdf_app_use_user_id_3862ba_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='useractivity',
            unique_together={('user', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='userbookmark',
            unique_together={('user', 'pdf')},
        ),
    ]
