# Generated by Django 5.2.3 on 2025-07-05 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_app', '0003_pdffile_is_solution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdffile',
            name='is_solution',
            field=models.BooleanField(default=False),
        ),
    ]
