# Generated by Django 5.2.3 on 2026-02-12 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_app', '0003_college_groupmessage_messagequota_otp_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('SUBSCRIPTION', 'Subscription (all premium PDFs)'), ('SINGLE_PDF', 'Single PDF'), ('SUBJECT_PACKAGE', 'Subject-wise package'), ('YEAR_PACKAGE', 'Year package')], default='SUBSCRIPTION', max_length=20),
        ),
        migrations.CreateModel(
            name='PDFPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. BBS 1st Year - Accountancy 2080', max_length=255)),
                ('package_type', models.CharField(choices=[('SUBJECT', 'Subject-wise (e.g. BBS 1st Year - Accountancy)'), ('YEAR', 'Year package (e.g. BBS 1st Year 2080 - All subjects)')], max_length=20)),
                ('year', models.PositiveIntegerField(help_text='Academic year e.g. 2080')),
                ('price', models.DecimalField(decimal_places=2, default=0, help_text='Package price', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pdfs', models.ManyToManyField(blank=True, help_text='Select all PDFs included in this package', related_name='packages', to='pdf_app.pdffile')),
                ('subject', models.ForeignKey(blank=True, help_text='Required for Subject-wise; leave blank for Year package', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='pdf_app.subject')),
            ],
            options={
                'verbose_name': 'PDF Package',
                'verbose_name_plural': 'PDF Packages',
                'ordering': ['-year', 'name'],
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='purchased_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='pdf_app.pdfpackage'),
        ),
    ]
