# Generated by Django 5.2.3 on 2026-02-12 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_app', '0004_add_pdf_package_and_payment_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('SUBSCRIPTION', 'Subscription (all premium PDFs)'), ('SINGLE_PDF', 'Single PDF'), ('SUBJECT_PACKAGE', 'Subject-wise package'), ('YEAR_PACKAGE', 'Single year package'), ('FULL_PACKAGE', 'Full package (all years 1–4 in one)')], default='SUBSCRIPTION', max_length=20),
        ),
        migrations.AlterField(
            model_name='pdfpackage',
            name='name',
            field=models.CharField(help_text='e.g. BBS 1st Year - Accountancy 2080, or BBS Full 1st-4th Year', max_length=255),
        ),
        migrations.AlterField(
            model_name='pdfpackage',
            name='package_type',
            field=models.CharField(choices=[('SUBJECT', 'Subject-wise (one subject, e.g. BBS 1st Year - Accountancy)'), ('YEAR', 'Single year package (one year, all subjects, e.g. BBS 1st Year 2080)'), ('ALL_YEARS', 'All years / Full package (1st, 2nd, 3rd, 4th year in one)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pdfpackage',
            name='subject',
            field=models.ForeignKey(blank=True, help_text='Required for Subject-wise only; leave blank for Year or All years', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='pdf_app.subject'),
        ),
        migrations.AlterField(
            model_name='pdfpackage',
            name='year',
            field=models.PositiveIntegerField(blank=True, help_text='For Single year: pick one year (e.g. 2080). Leave blank for Subject-wise or All years.', null=True),
        ),
    ]
