# Generated by Django 5.2.3 on 2026-02-12 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_app', '0007_add_is_solution_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdffile',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='For solution PDFs this is set to Rs 15 when Is Solution is ticked.', max_digits=10),
        ),
    ]
