# Generated by Django 5.2.3 on 2026-02-12 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_app', '0008_alter_pdffile_price'),
        ('pdf_app', '0008_solution_pdf_premium_and_price'),
    ]

    operations = [
    ]
