# Generated by Django 4.2.9 on 2026-02-15 07:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_app', '0012_pdffile_pdf_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdffile',
            name='is_approved',
            field=models.BooleanField(default=True, help_text='False = pending approval (student uploads). Only approved PDFs show in app.'),
        ),
        migrations.AddField(
            model_name='pdffile',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_pdfs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('SUBSCRIPTION', 'Subscription (all premium PDFs)'), ('SINGLE_PDF', 'Single PDF'), ('SUBJECT_PACKAGE', 'Subject package – one subject, all PDFs'), ('TOPIC_PACKAGE', 'Topic package – all subjects in one topic, all PDFs'), ('YEAR_PACKAGE', 'Single year package'), ('FULL_PACKAGE', 'Full package (all years 1–4 in one)')], default='SUBSCRIPTION', max_length=20),
        ),
        migrations.AlterField(
            model_name='pdffile',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Auto-set to Rs 15 for Solution / Question+Solution types.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='pdfpackage',
            name='content_type',
            field=models.CharField(choices=[('ALL', 'All PDFs (questions + solutions)'), ('QUESTIONS', 'Questions only'), ('SOLUTIONS', 'Solutions only')], default='ALL', help_text='Include: All PDFs, Questions only, or Solutions only.', max_length=20),
        ),
        migrations.AlterField(
            model_name='pdfpackage',
            name='is_solution_package',
            field=models.BooleanField(default=False, help_text='Set automatically when Content type is Solutions only (used by app API).'),
        ),
        migrations.AlterField(
            model_name='pdfpackage',
            name='name',
            field=models.CharField(help_text='e.g. Physics – All years, or TU – All subjects', max_length=255),
        ),
        migrations.AlterField(
            model_name='pdfpackage',
            name='package_type',
            field=models.CharField(choices=[('SUBJECT', 'Subject package – all PDFs in one subject (all years)'), ('TOPIC', 'Topic package – all subjects under one topic (all PDFs in that topic)'), ('YEAR', 'Year package – all PDFs in one year (all subjects)'), ('ALL_YEARS', 'Custom – select PDFs manually (optional)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pdfpackage',
            name='pdfs',
            field=models.ManyToManyField(blank=True, help_text='Auto-filled on Save. You can adjust after if needed.', related_name='packages', to='pdf_app.pdffile'),
        ),
        migrations.AlterField(
            model_name='pdfpackage',
            name='subject',
            field=models.ForeignKey(blank=True, help_text='For Subject package: select the subject. Leave empty for Topic/Year package.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='pdf_app.subject'),
        ),
        migrations.AlterField(
            model_name='pdfpackage',
            name='year',
            field=models.PositiveIntegerField(blank=True, help_text='For Year package: select the year. Leave empty for Topic/Subject package.', null=True),
        ),
    ]
