# Generated by Django 4.2.9 on 2026-02-15 08:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_app', '0013_add_student_pdf_upload_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='is_approved',
            field=models.BooleanField(default=True, help_text='False = pending (student-created). Only approved show in app.'),
        ),
        migrations.AddField(
            model_name='subject',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_subjects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='topic',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='is_approved',
            field=models.BooleanField(default=True, help_text='False = pending (student-created). Only approved show in app.'),
        ),
        migrations.AddField(
            model_name='topic',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_topics', to=settings.AUTH_USER_MODEL),
        ),
    ]
