# Generated by Django 4.2.9 on 2026-02-16 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_app', '0014_add_topic_subject_student_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('title', models.CharField(help_text='e.g. "Unit 1 – Mechanics"', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Order within same day')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routines', to='pdf_app.subject')),
            ],
            options={
                'ordering': ['subject', 'day_of_week', 'order', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True)),
                ('action_url', models.CharField(blank=True, help_text='Optional deep link or URL', max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('is_pinned', models.BooleanField(default=False, help_text='User pinned / saved for later')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='pdf_app.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserRoutineReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_minutes_before', models.PositiveSmallIntegerField(default=15, help_text='Send notification this many minutes before start_time')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_users', to='pdf_app.subjectroutine')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routine_reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user'], name='pdf_app_use_user_id_940243_idx')],
                'unique_together': {('user', 'routine')},
            },
        ),
        migrations.AddIndex(
            model_name='subjectroutine',
            index=models.Index(fields=['subject', 'day_of_week'], name='pdf_app_sub_subject_2d0585_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='subjectroutine',
            unique_together={('subject', 'day_of_week', 'start_time')},
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', '-created_at'], name='pdf_app_not_user_id_45f5fa_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='pdf_app_not_user_id_7a36bf_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_pinned'], name='pdf_app_not_user_id_2cc072_idx'),
        ),
    ]
