# Generated by Django 4.2.9 on 2026-02-16 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_app', '0015_add_notifications_and_routines'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='feed_posts/')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive posts are hidden from the app')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedPostLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='pdf_app.feedpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_likes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='feedpost',
            index=models.Index(fields=['is_active', '-created_at'], name='pdf_app_fee_is_acti_0aa097_idx'),
        ),
        migrations.AddIndex(
            model_name='feedpostlike',
            index=models.Index(fields=['post'], name='pdf_app_fee_post_id_970955_idx'),
        ),
        migrations.AddIndex(
            model_name='feedpostlike',
            index=models.Index(fields=['user'], name='pdf_app_fee_user_id_6fa5c3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='feedpostlike',
            unique_together={('user', 'post')},
        ),
    ]
