# Generated by Django 4.2.9 on 2026-02-18 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_app', '0016_add_feed_post_and_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedPostBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeedPostComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='feedpost',
            name='pdf_app_fee_is_acti_0aa097_idx',
        ),
        migrations.AddField(
            model_name='feedpost',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tu_notice_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedpost',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='APPROVED', help_text='User-created posts start as Pending; admin approves.', max_length=20),
        ),
        migrations.AddIndex(
            model_name='feedpost',
            index=models.Index(fields=['is_active', 'status', '-created_at'], name='pdf_app_fee_is_acti_cd5737_idx'),
        ),
        migrations.AddIndex(
            model_name='feedpost',
            index=models.Index(fields=['created_by'], name='pdf_app_fee_created_4caa4b_idx'),
        ),
        migrations.AddField(
            model_name='feedpostcomment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='pdf_app.feedpost'),
        ),
        migrations.AddField(
            model_name='feedpostcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedpostbookmark',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='pdf_app.feedpost'),
        ),
        migrations.AddField(
            model_name='feedpostbookmark',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_bookmarks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='feedpostcomment',
            index=models.Index(fields=['post'], name='pdf_app_fee_post_id_8ad80c_idx'),
        ),
        migrations.AddIndex(
            model_name='feedpostcomment',
            index=models.Index(fields=['user'], name='pdf_app_fee_user_id_bae050_idx'),
        ),
        migrations.AddIndex(
            model_name='feedpostbookmark',
            index=models.Index(fields=['post'], name='pdf_app_fee_post_id_f5b738_idx'),
        ),
        migrations.AddIndex(
            model_name='feedpostbookmark',
            index=models.Index(fields=['user'], name='pdf_app_fee_user_id_017b38_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='feedpostbookmark',
            unique_together={('user', 'post')},
        ),
    ]
