# Generated by Django 4.2.9 on 2026-02-19 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_app', '0017_tu_notice_feed_bookmark_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedPostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='feed_posts/')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Display order (0-based).')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pdf_app.feedpost')),
            ],
            options={
                'ordering': ['order'],
                'indexes': [models.Index(fields=['post'], name='pdf_app_fee_post_id_de812a_idx')],
            },
        ),
    ]
