# Generated by Django 4.2.9

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_app', '0018_feed_post_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(
                default=False,
                help_text='Verified account (blue tick). Set automatically when user buys any paid package, or manually by admin.'
            ),
        ),
    ]
