# Generated by Django 4.2.9 on 2026-02-24 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_app', '0019_user_is_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTopicUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('usage_count', models.PositiveIntegerField(default=0, help_text='Number of times user opened/viewed this topic (or PDFs under it) on this day.')),
                ('time_spent_minutes', models.PositiveIntegerField(default=0, help_text='Optional: minutes spent in this topic on this day.')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_usages', to='pdf_app.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_usages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User topic usage',
                'verbose_name_plural': 'User topic usage',
                'ordering': ['-date', '-usage_count'],
                'indexes': [models.Index(fields=['topic', '-date'], name='pdf_app_use_topic_i_01dd88_idx'), models.Index(fields=['user', '-date'], name='pdf_app_use_user_id_28cef4_idx')],
                'unique_together': {('user', 'topic', 'date')},
            },
        ),
    ]
