# Generated by Django 4.2.9 on 2026-02-26 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_app', '0022_user_last_seen'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='user',
            new_name='users_last_se_f59089_idx',
            old_name='users_last_s_idx',
        ),
        migrations.AddField(
            model_name='topic',
            name='program',
            field=models.CharField(blank=True, db_index=True, help_text='Program/course group (e.g. BBS, BSC, BBA). Used to group topics in app.', max_length=50),
        ),
        migrations.AddField(
            model_name='topic',
            name='year_label',
            field=models.CharField(blank=True, help_text='Year display (e.g. 1st Year, 2nd Year). Shown under program when user taps.', max_length=50),
        ),
    ]
